module.exports = {
    SEARCH_ARTIST_BY_NAME: 'GET_ARTIST_BY_NAME',
    SEARCH_ARTIST_BY_NAME_SUCCESS: 'GET_ARTIST_BY_NAME_SUCCESS',
    SEARCH_ARTIST_BY_NAME_FAILUER: 'GET_ARTIST_BY_NAME_FAILUER',
    SET_ARTIST_NAME: 'SET_ARTIST_NAME',
    GET_ARTIST_EVENTS: 'GET_ARTIST_EVENTS',
    GET_ARTIST_EVENTS_SUCCESS: 'GET_ARTIST_EVENTS_SUCCESS',
    GET_ARTIST_EVENTS_FAILURE: 'GET_ARTIST_EVENTS_FAILURE',
    IS_IN_AJAX_CALL:'IS_IN_AJAX_CALL'
}